# Spring application settings
spring:
  application:
    name: Birdnerd
  profiles:
    active: development
  servlet:
    multipart:
      max-file-size: 10MB

# Spring actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS
  info:
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true

# Birdnerd settings
birdnerd:
  dofbasen:
    speciesurl: https://dofbasen.dk/danmarksfugle/art/