# Server settings
server:
  port: "${PORT:8888}"

# Spring application settings
spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:/Users/hjep/.birdnerd/db/birdnerd
    driverClassName: org.h2.Driver
    username: birdnerd
    password: HaliaeetusAlbicilla
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

# Vaadin settings
vaadin:
  frontend:
    hotdeploy: false

# Logging settings
logging:
  level:
    org:
      atmosphere: ERROR
      springframework: WARN
      apache: WARN
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: WARN

# Birdnerd settings
birdnerd:
  doffile: /Users/hjep/.birdnerd/dof-species.csv
  imagepath: /Users/hjep/.birdnerd/images/