# Server settings
server:
  port: "${PORT:8080}"

# Spring application settings
spring:
  application:
    name: Birdnerd
  profiles:
    active: production
  servlet:
    multipart:
      max-file-size: 10MB
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:/Users/hjep/Development/Personal/birdnerd/db/birdnerd
    driverClassName: org.h2.Driver
    username: birdnerd
    password: HaliaeetusAlbicilla
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

# Spring actuator settings
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS
  info:
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true

# Vaadin settings
vaadin:
  frontend:
    hotdeploy: false

# Logging settings
logging:
  level:
    org:
      atmosphere: ERROR
      springframework: WARN
      apache: WARN
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: WARN

# Birdnerd settings
birdnerd:
  doffile: /Users/hjep/Development/Personal/birdnerd/src/main/resources/dof-species.csv
  imagepath: /Users/hjep/Development/Personal/birdnerd/tmp-images/